"""Ajout du champ max_attempts à Exercise

Revision ID: eba0f2150580
Revises: 
Create Date: 2025-04-28 20:40:18.090807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba0f2150580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.execute("UPDATE exercise SET max_attempts = 3 WHERE max_attempts IS NULL")
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('max_attempts', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('max_attempts')

    # ### end Alembic commands ###
